<a href="https://colab.research.google.com/github/jawakeavanti/Training_Projects_AvantiJ/blob/main/Project1_Fraud_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#loading the dataset
bank_data = pd.read_excel('Fraud_detection_data.xlsx',index_col="Transaction_ID")

In [3]:
bank_data.head()

,Customer_ID,Transaction_Amount,Location,Time_of_Day,Is_Fraudulent
Transaction_ID,,,,,
1,101,1000,Mumbai,Morning,0
2,102,500,Delhi,Afternoon,1
3,103,2000,Chennai,Evening,0
4,104,300,Gujarat,Morning,1
5,105,800,Bengalore,Afternoon,0

In [4]:
#checking the information of the data
bank_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 1 to 20
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         20 non-null     int64
 1   Transaction_Amount  20 non-null     int64
 2   Location            20 non-null     object
 3   Time_of_Day         20 non-null     object
 4   Is_Fraudulent       20 non-null     int64
dtypes: int64(3), object(2)
memory usage: 960.0+ bytes

In [5]:
#checking for nullvalues
bank_data.isnull().sum()

Customer_ID           0
Transaction_Amount    0
Location              0
Time_of_Day           0
Is_Fraudulent         0
dtype: int64

In [6]:
#checking the class distribution
bank_data['Is_Fraudulent'].value_counts()

Is_Fraudulent
0    12
1     8
Name: count, dtype: int64

In [7]:
# Class imbalance for non-fraudulent
# 0 = Non-Fraudulent
# 1 = Fraudulent

In [8]:
bank_data['Location'].value_counts()

Location
Mumbai       4
Delhi        4
Chennai      4
Gujarat      4
Bengalore    4
Name: count, dtype: int64

In [9]:
bank_data['Time_of_Day'].value_counts()

Time_of_Day
Morning      7
Afternoon    7
Evening      6
Name: count, dtype: int64

In [ ]:
#Converting or encoding the Time_of_Day and Location column using Label encoder (ordinal_data) and one_hot_encoder(nominal data)

In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
# Initialize the LabelEncoder
label_encoder = LabelEncoder()

In [12]:
Time_of_Day_encoded = label_encoder.fit_transform(bank_data['Time_of_Day'])

In [13]:
from sklearn.preprocessing import OneHotEncoder

In [14]:
one_hot_encoder =  OneHotEncoder(sparse=False)

In [15]:
Location_encoded = one_hot_encoder.fit_transform(bank_data[['Location']])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [16]:
bank_data['Time_of_Day_encoded'] = Time_of_Day_encoded

In [17]:
Location_encoded_df = pd.DataFrame(Location_encoded, columns=one_hot_encoder.get_feature_names_out(['Location']))
bank_data = pd.concat([bank_data, Location_encoded_df], axis=1)

In [18]:
bank_data

,Customer_ID,Transaction_Amount,Location,Time_of_Day,Is_Fraudulent,Time_of_Day_encoded,Location_Bengalore,Location_Chennai,Location_Delhi,Location_Gujarat,Location_Mumbai
1,101.0,1000.0,Mumbai,Morning,0.0,2.0,0.0,0.0,1.0,0.0,0.0
2,102.0,500.0,Delhi,Afternoon,1.0,0.0,0.0,1.0,0.0,0.0,0.0
3,103.0,2000.0,Chennai,Evening,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,104.0,300.0,Gujarat,Morning,1.0,2.0,1.0,0.0,0.0,0.0,0.0
5,105.0,800.0,Bengalore,Afternoon,0.0,0.0,0.0,0.0,0.0,0.0,1.0
6,106.0,1500.0,Mumbai,Evening,1.0,1.0,0.0,0.0,1.0,0.0,0.0
7,107.0,400.0,Delhi,Morning,0.0,2.0,0.0,1.0,0.0,0.0,0.0
8,108.0,2500.0,Chennai,Afternoon,1.0,0.0,0.0,0.0,0.0,1.0,0.0
9,109.0,700.0,Gujarat,Evening,0.0,1.0,1.0,0.0,0.0,0.0,0.0
10,110.0,1200.0,Bengalore,Morning,0.0,2.0,0.0,0.0,0.0,0.0,1.0
11,111.0,1800.0,Mumbai,Afternoon,1.0,0.0,0.0,0.0,1.0,0.0,0.0
12,112.0,2200.0,Delhi,Evening,0.0,1.0,0.0,1.0,0.0,0.0,0.0
13,113.0,350.0,Chennai,Morning,1.0,2.0,0.0,0.0,0.0,1.0,0.0
14,114.0,3000.0,Gujarat,Afternoon,0.0,0.0,1.0,0.0,0.0,0.0,0.0
15,115.0,400.0,Bengalore,Evening,1.0,1.0,0.0,0.0,0.0,0.0,1.0
16,116.0,800.0,Mumbai,Morning,0.0,2.0,0.0,0.0,1.0,0.0,0.0
17,117.0,1300.0,Delhi,Afternoon,0.0,0.0,0.0,1.0,0.0,0.0,0.0
18,118.0,1700.0,Chennai,Evening,0.0,1.0,0.0,0.0,0.0,1.0,0.0
19,119.0,500.0,Gujarat,Morning,1.0,2.0,1.0,0.0,0.0,0.0,0.0
20,120.0,900.0,Bengalore,Afternoon,0.0,0.0,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0

In [19]:
#dropping the original columns and last NAN row
bank_data_cleaned = bank_data.drop(columns=['Location','Time_of_Day'], axis=1)

In [20]:
bank_data_cleaned = bank_data_cleaned.dropna()

In [21]:
bank_data_cleaned

,Customer_ID,Transaction_Amount,Is_Fraudulent,Time_of_Day_encoded,Location_Bengalore,Location_Chennai,Location_Delhi,Location_Gujarat,Location_Mumbai
1,101.0,1000.0,0.0,2.0,0.0,0.0,1.0,0.0,0.0
2,102.0,500.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
3,103.0,2000.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,104.0,300.0,1.0,2.0,1.0,0.0,0.0,0.0,0.0
5,105.0,800.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
6,106.0,1500.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
7,107.0,400.0,0.0,2.0,0.0,1.0,0.0,0.0,0.0
8,108.0,2500.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
9,109.0,700.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
10,110.0,1200.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0
11,111.0,1800.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
12,112.0,2200.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
13,113.0,350.0,1.0,2.0,0.0,0.0,0.0,1.0,0.0
14,114.0,3000.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
15,115.0,400.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
16,116.0,800.0,0.0,2.0,0.0,0.0,1.0,0.0,0.0
17,117.0,1300.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
18,118.0,1700.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
19,119.0,500.0,1.0,2.0,1.0,0.0,0.0,0.0,0.0

In [22]:
bank_data_cleaned['Is_Fraudulent'].value_counts()

Is_Fraudulent
0.0    11
1.0     8
Name: count, dtype: int64

In [23]:
#separating datasets
legit = bank_data_cleaned[bank_data_cleaned['Is_Fraudulent']==0]
fraud = bank_data_cleaned[bank_data_cleaned['Is_Fraudulent']==1]

In [24]:
fraud.shape

(8, 9)

In [25]:
legit.shape

(11, 9)

In [26]:
#Undersampling
legit_sample = legit.sample(n=8)

In [27]:
new_data = pd.concat([legit_sample, fraud], axis=0)

In [28]:
new_data

,Customer_ID,Transaction_Amount,Is_Fraudulent,Time_of_Day_encoded,Location_Bengalore,Location_Chennai,Location_Delhi,Location_Gujarat,Location_Mumbai
12,112.0,2200.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
3,103.0,2000.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
5,105.0,800.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
9,109.0,700.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
18,118.0,1700.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
14,114.0,3000.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
10,110.0,1200.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0
7,107.0,400.0,0.0,2.0,0.0,1.0,0.0,0.0,0.0
2,102.0,500.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
4,104.0,300.0,1.0,2.0,1.0,0.0,0.0,0.0,0.0
6,106.0,1500.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
8,108.0,2500.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
11,111.0,1800.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
13,113.0,350.0,1.0,2.0,0.0,0.0,0.0,1.0,0.0
15,115.0,400.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
19,119.0,500.0,1.0,2.0,1.0,0.0,0.0,0.0,0.0

In [29]:
new_data['Is_Fraudulent'].value_counts()

Is_Fraudulent
0.0    8
1.0    8
Name: count, dtype: int64

In [30]:
#Spliting the dataset and feature
X= new_data.drop(columns='Is_Fraudulent', axis=1)
y= new_data['Is_Fraudulent']

In [31]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [41]:
#training the model
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, stratify=y, random_state=102)

In [42]:
lr = LogisticRegression()

In [43]:
lr.fit(X_train, y_train)

LogisticRegression()

In [44]:
#Model Evaluation

#Accuracy Testing

X_train_prediction = lr.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, y_train)

In [45]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.7142857142857143

In [46]:
# accuracy on test data
X_test_prediction = lr.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, y_test)

In [47]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  1.0

In [ ]:
# As the dataset is small, i have taken train and test split as 90-10

# with 80-20 split the accuracy
#train - 0.85
#test - 0.76